### PR TITLE
Build instruction

### PR DESCRIPTION
**Pull request by bogdangi**
It adds build instruction that helps me to start working on this plugin.
I am not ruby developer bu we are using it for our production environment.

### CODE REVIEW

**Comment by KenanSulayman** [comment]
Any updates on this? Can this be merged?

**Comment by BrendonEarl** [comment]
Bump - any updates on this?
Looks like it resolves the bug where one document is lost when moving data from MongoDB to ElasticSearch, which would be a huge help in our environment.

**Comment by phutchins** [comment]
Hey @bogdangi and @KenanSulayman, looking at this one now.

**Comment by phutchins** [comment]
Merged, thanks!

**Pull request merged**
