### PR TITLE
[FIX] Enable store all types of variables.

### PR DESCRIPTION
**Pull request by kurkop**
This enable store "arrays" and other types of variables.

### CODE REVIEW

**Comment by phutchins** [comment]
@kurkop I'd like to make this an option and possibly default to this. Older versions of logstash couldn't view certain types of non string data and up to date versions also cannot view some so this may be a breaking change for some...

**Comment by phutchins** [comment]
@kurkop could you update this to make it an option?

**Comment by phutchins** [comment]
@kurkop why closed?

**Comment by kurkop** [comment]
@phutchins is replaced by https://github.com/phutchins/logstash-input-mongodb/pull/64

**Pull request closed without merging**
