### PR TITLE
output the isodate on flatten

### PR DESCRIPTION
**Pull request by zqzjz0911**
this can make the @timestamp into isodate instead of  UTC format string

### CODE REVIEW

**Comment by phutchins** [comment]
Hi @zqzjz0911 so sorry I missed this before. Just noticed it now... Talking a look. 

Could you give a little detail on what your goal was here?

**Comment by zqzjz0911** [comment]
there is a problem when i use this mongodb input plugin and ouput into the elasticsearch , the field which type is time, will translate to a  UTC format string, an this  UTC format string can't be sorted correctly.

**Comment by phutchins** [comment]
Sorry for the delay on this. Merging this now. We need to get some tests in this plugin...

**Comment by zqzjz0911** [comment]
thx.

**Pull request merged**
